CREATE DATABASE Restaurante_Pratos;

USE Restaurante_Pratos;

CREATE TABLE Pratos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(200) NOT NULL,
    Preco DECIMAL(10,2) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL
);

CREATE TABLE Usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(200) NOT NULL
);